### ISSUE TITLE
There were some errors when running this code, and I fixed them myself.

### ISSUE THREAD

**Issue by tralv1612** [makerviet/tfs-data-centric#4]
“When running the command ‘pip install -e .’, the following error will appear and I opened the setup.py file and edited the function get_package_dir() ‘yolox.exp.default’: ‘exps/default’ to ‘yolox.exp.default’: ‘yolox/exp/default’. I hope the organizing committee will review the above code
Obtaining file:///content/tfs-data-centric
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by vietanhdev** [comment]
@tralv1612 Fixed in the `main` branch. Please check it and feedback.
Thank you!

We also added a Colab notebook for training: [https://colab.research.google.com/github/makerviet/tfs-data-centric/blob/main/notebook.ipynb](https://colab.research.google.com/github/makerviet/tfs-data-centric/blob/main/notebook.ipynb).

**Comment by tralv1612** [comment]
When I ran the sample dataset, there were no errors, but when I ran my own dataset, I encountered the following error. I used Roboflow to export it in COCO format. I hope you can help me.

2023-08-05 03:43:21 | INFO     | yolox.core.trainer:208 - ---> start train epoch1
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [0,0,0], thread: [0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
2023-08-05 03:43:22 | INFO     | yolox.core.trainer:200 - Training of experiment is done and the best AP is 0.00
2023-08-05 03:43:22 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (5046), thread 'MainThread' (134737898332160):
Traceback (most recent call last):

  File "/content/tfs-data-centric/tools/train.py", line 156, in <module>
    launch(
    └ <function launch at 0x7a8a7b2ae8c0>

> File "/content/tfs-data-centric/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7a8a6d5d4790>

**Comment by tralv1612** [comment]
@vietanhdev I was able to run the code, thank you!
