### ISSUE TITLE
Please provide docker image

### ISSUE THREAD

**Issue by pphuc25** [makerviet/tfs-data-centric#5]
When running on Linux training code work well for training but not in Window, I think providing a docker will help everyone to run easier, really need a docker.

**Comment by vietanhdev** [comment]
@pphuc25 Please try Anaconda to create a training env.
You can also use Colab notebook for training: https://colab.research.google.com/github/makerviet/tfs-data-centric/blob/main/notebook.ipynb.

**Comment by pphuc25** [comment]
@vietanhdev As I mentioned before, some of the command lines do not work in Windows so it's better if we can have a docker image
